BulletSubject component (new)
leemonade/bubbles pull request #108
Opened 2023-08-16 09:53 UTC by fermarinsanchez

2023-08-16 11:01 UTC, MIGUELez11 requested changes
Please review the comments, then, i'll re-review it 😋.

PS: I think the component is not correctly exported. Does `pacakges/components/src/misc/index.js` have an export for `BulletSubject`?

2023-08-16 15:18 UTC, fermarinsanchez commented on packages/components/src/misc/BulletSubject/BulletSubject.js
> +  console.log(iconToShow);
removed!

2023-08-16 15:18 UTC, fermarinsanchez commented on packages/components/src/misc/BulletSubject/BulletSubject.styles.js
> +  console.log(theme.other);
removed!

2023-08-16 15:26 UTC, fermarinsanchez commented on packages/components/src/misc/BulletSubject/BulletSubject.js
> +          alt="subject icon"
Totally true. The component now receive a new property for alt text and the default property is "subject icon".

2023-08-29 09:32 UTC, MIGUELez11 approved these changes
Looks right to me 😄

2023-08-29 09:34 UTC, merged